package com.elephant.generics.watercolors;

/**
 * Created by elephant on 16/4/3.
 */
public enum  Watercolors {
	ZINC, LEMON_YELLO, MEDIUM_YELLO, DEEP_YELLO, ORANGE,
	BRILLIANT_RED,CRIMSON,MAGENTA,ROSE_MADDER,VIOLET,
	CERULEAN_BLUE_HUE,PHTHALO_BLUE,ULTRAMARINE,
	COBALT_BLUE_HUE,PERMANENT_GREEN,VIRIDIAN_HUE,
	SPA_GREEN,YELLO_OCHRE,BURNT_SIENNA,RAW_UMBER,
	BURNT_UMBER,PAYNES_GRAY,IVORY_BLACK
}
